manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        # Additional modules containing boards/shields/custom code can be listed here as well
        # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
        #-----
        # support nice_oled and nice_epaper
        - name: LordPinkFloyd
          url-base: https://github.com/LordPinkFloyd
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: main
          import: app/west.yml
        # support nice_oled and nice_epaper
        - name: zmk-nice-oled
          remote: LordPinkFloyd
          revision: deletrius
    self:
        path: config
